## {{ ansible_managed }}

{% for key, value in rsyncd_conf_global.items() %}
{{ key }} = {{ value }}
{% endfor %}

{% for module, config in rsyncd_conf_modules.items() %}
[{{ module }}]
{% for key, value in config.items() %}
  {{ key }} = {{ value }}
{% endfor %}
{% endfor %}
