---
- name: ensure apt conf directory
  file:
    state: directory
    path: "{{ apt_conf_dir }}"
    owner: root
    group: root
    mode: 0755
  tags: [apt-proxy]

- name: configure apt proxy
  template:
    dest: "{{ apt_http_proxy_conf }}"
    owner: root
    group: root
    mode: 0644
    src: config.j2
  tags: [apt-proxy]
