---
- name: restart wireguard
  service:
    name: wg-quick@{{ wireguard_interface }}
    state: restarted

- name: apply iptables rules
  shell: /etc/iptables/iptables-wg-up-{{ wireguard_interface }}.sh
