---
- name: configure directories
  file:
    path: "{{ item.directory }}"
    owner: "{{ item.user | default('root') }}"
    group: "{{ item.user | default('root') }}"
    mode: "0750"
    state: directory
  loop: "{{ docker_compose_stacks_v0 }}"
  loop_control:
    label: "{{ item.directory }}"
  tags: [stacks, directories]

- name: configure template files
  template:
    src: "{{ item.1.template }}"
    dest: "{{ item.0.directory }}/{{ item.1.path }}"
    owner: "{{ item.user | default('root') }}"
    group: "{{ item.user | default('root') }}"
    mode: "{{ item.1.mode | default('0640') }}"
  loop: "{{ docker_compose_stacks_v0 | subelements('templates') }}"
  loop_control:
    label: "{{ item.0.directory }} -> {{ item.1.path }}"
  register: update_templates
  tags: [stacks, templates]

- name: run docker compose
  shell:
    cmd: "{{ docker_compose_cmd }}"
    chdir: "{{ item.directory }}"
  when: docker_compose_cmd | trim != 'invalid'
  loop: "{{ docker_compose_stacks_v0 }}"
  loop_control:
    index_var: item_idx
    label: "{{ item.directory }} ({{ item.state | default('present') }}) -> {{ docker_compose_cmd | trim }}"
  tags: [stacks]
