---
# node exporter version
node_exporter_image: quay.io/prometheus/node-exporter:v1.9.1

# runtime configuration
node_exporter_dir: /opt/node-exporter
node_exporter_web_listen_address: ":9100"
node_exporter_run_as_user: "9100"

# allow overriding config templates
node_exporter_docker_compose_template: docker-compose.yaml.j2

# [optional] enable systemd collector (NOTE: this forces node_exporter_run_as_user=0)
node_exporter_enable_systemd_collector: true
