---
- name: install apt-cacher
  package:
    update_cache: true
    name: apt-cacher
  tags: [apt-cacher, packages]

- name: ensure apt-cacher config directory
  file:
    state: directory
    path: "{{ apt_cacher_conf_d }}"
    owner: root
    group: root
    mode: 0755
  tags: [apt-cacher, config]

- name: configure apt-cacher
  template:
    dest: "{{ apt_cacher_conf_d }}/{{ item.key }}"
    owner: root
    group: root
    mode: 0644
    src: config.j2
  loop: "{{ apt_cacher_configs | dict2items }}"
  notify:
    - restart apt-cacher
  tags: [apt-cacher, configs]

- name: enable apt-cacher service
  service:
    name: apt-cacher
    enabled: true
  tags: [apt-cacher, service]
