---
node_exporter_textfile_dir: /var/lib/node_exporter
node_exporter_textfile_crons:
  apt:
    enabled: "{{ inventory_hostname in (groups['ubuntu'] + groups['debian']) }}"
    cron: 0 * * * *
    script: https://raw.githubusercontent.com/prometheus-community/node-exporter-textfile-collector-scripts/414fb44693444cb96a55c7152cdd84d531888e1f/apt.sh
  yum:
    enabled: "{{ inventory_hostname in (groups['centos'] + groups['rocky'] }}"
    cron: 0 * * * *
    script: https://raw.githubusercontent.com/prometheus-community/node-exporter-textfile-collector-scripts/414fb44693444cb96a55c7152cdd84d531888e1f/yum.sh
