- name: ensure directory
  file:
    state: directory
    path: "{{ alertmanager_dir }}"
    mode: "0755"
    owner: root
    group: root
  tags: [alertmanager]

- name: ensure alertmanager image
  command:
    cmd: sudo docker pull {{ alertmanager_image | quote }}
  register: docker_pull
  changed_when: "'Downloaded newer image' in docker_pull.stdout"
  tags: [alertmanager]

- name: render docker-compose
  template:
    src: "{{ alertmanager_docker_compose_template }}"
    dest: "{{ alertmanager_dir }}/docker-compose.yaml"
    mode: "0644"
    owner: root
    group: root
  notify: restart alertmanager
  tags: [alertmanager]

- name: render alertmanager configuration
  template:
    src: "{{ alertmanager_config_template }}"
    dest: "{{ alertmanager_dir }}/config.yaml"
    mode: "0400"
    owner: "{{ alertmanager_run_as_user }}"
    group: "{{ alertmanager_run_as_user }}"
    validate: "{{ alertmanager_validate_config_cmd }}"
  notify: restart alertmanager
  tags: [alertmanager]

- name: create alertmanager data dir
  file:
    state: directory
    path: "{{ alertmanager_dir }}/data"
    mode: "0755"
    owner: "{{ alertmanager_run_as_user }}"
    group: "{{ alertmanager_run_as_user }}"
  tags: [alertmanager]
