---
- name: download rke2
  environment:
    INSTALL_RKE2_TYPE: agent
  shell:
    cmd: |
      curl https://get.rke2.io -L | sh -
    creates: /usr/local/bin/rke2-uninstall.sh
  tags: [rke2, worker]

- name: configure rke2-agent service
  lineinfile:
    path: "{{ rke2_agent_env[ansible_distribution | lower] }}"
    line: "{{ item }}"
  no_log: true
  loop:
    - RKE2_URL="https://{{ groups.rke2_init[0] }}:9345"
    - RKE2_TOKEN="{{ rke2_token }}"
  notify:
    - restart rke2-agent
  tags: [rke2, worker, config]

- name: enable rke2-agent
  when: "'rke2-agent.service' not in services"
  service:
    name: "{{ rke2_agent_service[ansible_distribution | lower] }}"
    enabled: true
  tags: [rke2, worker, service]

- name: force handlers
  meta: flush_handlers
  tags: [rke2, worker, service]
