---
# VPN subnet "10.8.0.0/24" is specified as "10.8.0"
vpn_subnet: 10.8.0

user_vpn_clients: [client-1, client-2]

# VPN should push a default route to clients
vpn_default_gateway: false

# Route extra networks via the VPN
vpn_networks:
- network: 172.16.1.0
  mask: 255.255.255.0

vpn_create_server_clients: false

# Preconfigure IP assignments for client names.
# This will be written at /etc/openvpn/ipp.txt if not empty. For example,
#
# vpn_preconfigure_ipp: |
#   client-1 10.10.1.11
#   client-2 10.10.1.12
#   client-3 10.10.1.13
vpn_preconfigure_ipp: ""
