---
wireguard_port: 50000

wireguard_interface: wg0

wireguard_subnet_size: 24

wireguard_persistent_keepalive: 20

# wireguard_peers is a dict of hosts to configure as peers in the wireguard vpn
# wireguard_peers:
#   host-1: { ip: 10.10.1.1, privkey: "$(wg genkey)", pubkey: "$(echo $privkey | wg pubkey)", networks: [10.100.0.0/16], endpoint: "$publicip:{{ wireguard_port }}"}
#   host-2: { ip: 10.10.1.2, privkey: "$(wg genkey)", pubkey: "$(echo $privkey | wg pubkey)", networks: [10.101.0.0/16] }
#   host-3: { ip: 10.10.1.3, privkey: "$(wg genkey)", pubkey: "$(echo $privkey | wg pubkey)" }

#   client-0: { ip: 10.10.1.100, privkey: "$(wg genkey)", pubkey: "$(echo $privkey | wg pubkey)" }
wireguard_peers: {}

# wireguard_clients is a list of clients to create. each client file will be created at the specified host and path
# wireguard_clients:
#   client-0: { host: localhost, path: wg.conf, owner: ubuntu }
wireguard_clients: {}
