---
# cephadm release to install, e.g. "tentacle", "squid". if not specified, uses the distro default
cephadm_release: ""

# fail if cephadm check-host is not successful
cephadm_check_host: true

# install ceph-common package
cephadm_install_ceph_common: true

# install ceph-volume package
cephadm_install_ceph_volume: false
