---
- name: copy netplan configuration
  template:
    src: netplan_fragment.yml.j2
    dest: "{{ netplan_config_dir }}/{{ item.key }}"
    owner: "root"
    group: "root"
    mode: "0440"
  loop: "{{ netplan_fragments | dict2items }}"
  when: (item.value.state | default('present')) == 'present'
  register: netplan_config_present
  notify:
  - netplan apply
  - clear facts
  tags: [netplan]

- name: cleanup netplan configuration
  file:
    path: "{{ netplan_config_dir }}/{{ item.key }}"
    state: absent
  loop: "{{ netplan_fragments | dict2items }}"
  when: (item.value.state | default('present')) == 'absent'
  register: netplan_config_absent
  notify:
  - netplan apply
  - clear facts
  tags: [netplan]
