---
- name: disable module
  community.general.modprobe:
    name: "{{ item }}"
    state: absent
  loop: "{{ kernel_modules_disable }}"
  tags: [kernel, modules]

- name: blacklist module
  community.general.kernel_blacklist:
    name: "{{ item }}"
    state: present
  loop: "{{ kernel_modules_disable }}"
  tags: [kernel, modules]
