---
netdata_repository_channel: stable
netdata_repository_url: "https://repository.netdata.cloud/repos/{{ netdata_repository_channel }}/{{ ansible_distribution | lower }}"
netdata_repository_signing_key_url: https://repository.netdata.cloud/netdatabot.gpg.key
netdata_repository_signing_key_path: /usr/share/keyrings/netdata-archive-keyring.asc
netdata_apt_cache_valid_time: 3600

netdata_conf_dir: /etc/netdata
netdata_conf: |
  [global]
    bind socket to IP = localhost

# enable Slack notifications
netdata_slack_notifications_enabled: false
netdata_slack_webhook_url: "https://hooks.slack.com/services/AAAAAAAA/BBBBBBBB/CCCCCCCCCCCCCCCCCCCCCC"
netdata_slack_webhook_recepient: "#channel-name"

# list of managed netdata configuration files
# netdata_conf_files:
#   - name: go.d.conf
#     template: "{{ playbook_dir }}/templates/go.d.conf"
#   - name: go.d/httpcheck.conf
#     template: "{{ playbook_dir }}/templates/go.d/httpcheck.conf"
#   - name: toremove.conf
#     state: absent
netdata_conf_files: []
