---
sudo_group_distro:
  ubuntu: sudo
  debian: sudo
  centos: wheel
  rocky: wheel

sudo_group: "{{ sudo_group_distro[ansible_distribution | lower] | default('') }}"

# configure dotfiles for users, pulled from `files/`
# user_dotfiles:
#   - {user: ubuntu, file: .bashrc, mode: "0644"}
#   - {user: ubuntu, file: .vimrc, mode: "0644"}
user_dotfiles: []

# configure users and sudoers
# users_and_groups:
#   users:
#     - {name: ubuntu, groups: ["{{ sudo_group }}"], ssh_key: "{{ ubuntu_key }}"}
#     - {name: user_with_password, password: "{{ safe_password }}", groups: ["{{ sudo_group }}"]}
#   sudoers:
#     - {name: ubuntu, user: "%ubuntu", runas: "ALL=(ALL)", commands: "NOPASSWD: ALL"}

users_and_groups:
  users: []
  sudoers: []
