---
- name: install prerequisites
  package:
    name: yum-utils
    state: present
  tags: [docker, prerequisites]

- name: add docker repository
  shell: |
    yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  tags: [docker, repository]

- name: install docker
  package:
    name: "{{ docker_packages }}"
    update_cache: true
    state: present
  tags: [docker, packages]

- name: start docker
  service:
    name: docker
    state: started
  tags: [docker, service]
