---
- name: install prerequisites
  package:
    name: "{{ docker_dependencies }}"
    state: present
  tags: [docker, prerequisites]

- name: add docker repository key
  become: true
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    state: present
  tags: [docker, repo]

- name: add docker repository
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker-ce
  tags: [docker, repo]

- name: install docker
  become: true
  apt:
    name: "{{ docker_packages }}"
    update_cache: true
    state: present
  tags: [docker, packages]
