---
- name: gather ansible system facts
  setup:
    gather_subset: hardware
  tags: [docker]

- name: ensure docker daemon configuration directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: docker_daemon_config_json
  tags: [docker]

- name: configure docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  when: docker_daemon_config_json
  notify: restart docker
  tags: [docker]

- name: install docker for ubuntu/debian
  when: ansible_distribution in ['Ubuntu', 'Debian']
  include_tasks: debian.yml
  tags: [docker]

- name: install docker for centos/rocky
  when: ansible_distribution in ['CentOS', 'Rocky']
  include_tasks: centos.yml
  tags: [docker]

- name: install docker-compose
  become: true
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  tags: [docker, compose]

- name: add user to docker group
  user:
    append: yes
    groups: [docker]
    name: "{{ ansible_user }}"
  tags: [docker, group]
