---
- name: gather ansible system facts
  setup:
    gather_subset: hardware
  tags: [docker]

- name: install docker for ubuntu/debian
  when: ansible_distribution in ['Ubuntu', 'Debian']
  include_tasks: debian.yml
  tags: [docker]

- name: install docker for centos
  when: ansible_distribution in ['CentOS']
  include_tasks: centos.yml
  tags: [docker]

- name: install docker-compose
  become: true
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    owner: root
    group: root
    mode: 0755
  tags: [docker, compose]

- name: add user to docker group
  user:
    append: yes
    groups: [docker]
    name: "{{ ansible_user }}"
  tags: [docker, group]
