---
# prometheus version
prometheus_image: quay.io/prometheus/prometheus:v3.5.0

# runtime configuration
prometheus_dir: /opt/prometheus
prometheus_web_listen_address: ":9090"
prometheus_run_as_user: "9090"

# allow overriding config templates
prometheus_docker_compose_template: docker-compose.yaml.j2
prometheus_config_template: prometheus.yaml.j2

# prometheus_extra_args are passed to the prometheus binary
#
# prometheus_extra_args:
# - --storage.tsdb.retention.size=2GB
# - --storage.tsdb.retention.time=7d
# - --web.route-prefix=/prometheus/
# - --web.external-url=https://example.com/prometheus/
prometheus_extra_args: []

# prometheus scrape targets, passed through to the configuration file
#
# prometheus_scrape_configs:
# - job_name: node
#   static_configs:
#   - targets:
#     - node1:9100
#     - node2:9100
prometheus_scrape_configs: []

# prometheus alertmanager configuration, passed through to the configuration file
#
# prometheus_alertmanager_configs:
# - path_prefix: /alertmanager/
#   scheme: http
#   static_configs:
#   - targets:
#     - alertmanager:9093
prometheus_alertmanager_configs: []

# prometheus alert rule files
prometheus_alert_rules_files:
  - "{{ playbook_dir }}/files/prometheus/rules/*.rules"

# external labels to apply to all metrics
#
# prometheus_external_labels:
#   env: production
prometheus_external_labels: {}

# prometheus_validate_config_cmd is used to validate config files (replaced by %s)
# set to empty string to disable validation.
#
# prometheus_validate_config_cmd: ""
prometheus_validate_config_cmd: |
  bash -c '
    sudo docker run --rm -i --user=0 -v %s:/config:ro --entrypoint /bin/promtool {{ prometheus_image | quote }} check config /config
  '

# prometheus_validate_rules_cmd is used to validate rule files (replaced by %s)
# set to empty string to disable validation.
#
# prometheus_validate_rules_cmd: ""
prometheus_validate_rules_cmd: |
  bash -c '
    cat %s | sudo docker run --rm -i --entrypoint /bin/promtool {{ prometheus_image | quote }} check rules
  '
