- name: restart prometheus
  command:
    cmd: sudo docker-compose up -d --force-recreate
    chdir: "{{ prometheus_dir }}"

- name: reload prometheus
  shell:
    cmd: |
      if [ -z "$(sudo docker-compose top)" ]; then
        sudo docker-compose up -d --force-recreate
      else
        sudo docker-compose kill --signal SIGHUP prometheus
      fi
    chdir: "{{ prometheus_dir }}"
