---
- name: install wireguard tools
  # package:
  #   name: wireguard-tools
  apt:
    name: wireguard-tools
    update_cache: true
    install_recommends: false
  tags: [wireguard, install]

- name: configure wireguard
  template:
    src: wg.conf.j2
    dest: /etc/wireguard/{{ wireguard_interface }}.conf
    owner: root
    group: root
    mode: 0400
  vars:
    generate_client_name: "{{ inventory_hostname }}"
  notify: restart wireguard
  tags: [wireguard, config]

- name: configure wireguard clients
  delegate_to: "{{ item.value['host'] }}"
  template:
    src: wg.conf.j2
    dest: "{{ item.value['path'] }}"
    owner: "{{ item.value['owner'] | default('root') }}"
    group: "{{ item.value['owner'] | default('root') }}"
    mode: 0400
  loop: "{{ wireguard_clients | dict2items }}"
  when:
   - "'endpoint' in wireguard_peers[inventory_hostname]"
  vars:
    generate_client_name: "{{ item.key }}"

- name: enable ipv4 forward for servers
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: true
  when:
   - "'endpoint' in wireguard_peers[inventory_hostname]"
  tags: [wireguard, sysctl]

- name: ensure /etc/iptables exists
  file:
    path: /etc/iptables
    owner: root
    group: root
    mode: 0755
    state: directory
  when:
    - "'networks' in wireguard_peers[inventory_hostname]"
  tags: [wireguard, iptables]

- name: generate iptables masquerade scripts for peer networks
  template:
    src: iptables-wg-{{ item }}.sh.j2
    dest: /etc/iptables/iptables-wg-{{ item }}-{{ wireguard_interface }}.sh
    mode: 0500
    owner: root
    group: root
  loop: [up, down]
  when:
    - "'networks' in wireguard_peers[inventory_hostname]"
  notify: apply iptables rules
  tags: [wireguard, iptables]

- name: configure iptables service
  template:
    src: iptables-wg@.service.j2
    dest: /etc/systemd/system/iptables-wg@.service
    mode: 0644
    owner: root
    group: root
  when:
    - "'networks' in wireguard_peers[inventory_hostname]"
  tags: [wireguard, iptables]

- name: enable iptables service
  service:
    name: iptables-wg@{{ wireguard_interface }}
    enabled: true
  when:
    - "'networks' in wireguard_peers[inventory_hostname]"
  tags: [wireguard, iptables]

- name: enable wireguard
  service:
    name: wg-quick@{{ wireguard_interface }}
    enabled: true
  notify: restart wireguard
  tags: [wireguard, service]
